baseURL = "http://www.viveksyngh.info/blog"
languageCode = "en-us"
title = "Vivek Kumar Singh"
theme = "purehugo"
Paginate = 10
disqusShortname = "viveksynghblog"
publishdir = "docs"

[params]
  twitterName = "viveksyngh"
  githubName = "viveksyngh"
  description = "Pythonista, Gopher, Rookie Data Scientist"
  stackOverflowId = "2798036"
  linkedinName = "viveksyngh"
  google_analytics = "UA-113545356-1"
  hideShareOptions = true
  facebook = true
  googleplus = true
  twitter = true
